### PR TITLE
Change ASSET_PATH to make asset urls work correctly

### LINKED ISSUE #27: bangaloreruby.org fails to load assets
This is what I got in console when I go to http://bangaloreruby.org

```
http://bangaloreruby.org/assets/themes//css/style.css Failed to load resource: the server responded with a status of 404 (Not Found)
modernizr.min.js:4 'webkitIndexedDB' is deprecated. Please use 'indexedDB' instead.
r.indexedDB @ modernizr.min.js:4
(index):152 The deviceorientation event is deprecated on insecure origins, and support will be removed in the future. You should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.
(anonymous) @ (index):152
http://bangaloreruby.org/assets/themes//images/ruby_normal.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://img1.meetupstatic.com/9260736631256287675/img/star_450.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://img1.meetupstatic.com/84869143793177372874/img/birddog/everywhere_widget.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://bangaloreruby.org/favicon.ico Failed to load resource: the server responded with a status of 404 (Not Found)
http://bangaloreruby.org/assets/themes//css/style.css Failed to load resource: the server responded with a status of 404 (Not Found)
```

### PR DESCRIPTION
**Pull request by Roshanjossey**
Changed ASSET_PATH

fixes #27

### CODE REVIEW

**Comment by hemanth** [comment]
Thank you.

**Comment by Roshanjossey** [comment]
Awesome @hemanth, the funniest part is that it doesn't work correctly in local now. We might have to change something in Jekyll

**Comment by Roshanjossey** [comment]
Also thanks to @arunagw for guiding me to the right path.

**Comment by hemanth** [comment]
image

**Pull request merged**
